### ISSUE TITLE
Error copying/setting gitlab root password in gitlab-postconfig play

### ISSUE THREAD

**Issue by aenertia** [mgmt-sa-tiger-team/skylight#93]
Over the last week something has changed either in gitlab deploys or ansible to cause the gitlab-postconfig copy root password task to fail. 

Output:

```
TASK [gitlab-postconfig : GitLab Post | Check if root user password is set] *****************************************************************************************************
fatal: [gitlab]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

TASK [gitlab-postconfig : GitLab Post | Copy root password script to host] ******************************************************************************************************
changed: [gitlab]

TASK [gitlab-postconfig : GitLab Post | Execute set root password] **************************************************************************************************************
fatal: [gitlab]: FAILED! => {"changed": true, "cmd": ["./set_root_pw.sh"], "delta": "0:00:01.519606", "end": "2020-02-26 08:52:58.724467", "msg": "non-zero return code", "rc": 1, "start": "2020-02-26 08:52:57.204861", "stderr": "/opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:506:in `handle_argument_error': ERROR: \"rails console\" was called with arguments [\"production\"] (Thor::InvocationError)\nUsage: \"rails console [options]\"\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:34:in `rescue in run'\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:20:in `run'\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/command/base.rb:69:in `perform'\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/command.rb:46:in `invoke'\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/commands.rb:18:in `<top (required)>'\n\tfrom bin/rails:4:in `require'\n\tfrom bin/rails:4:in `<main>'\n/opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/commands/console/console_command.rb:95:in `perform': wrong number of arguments (given 1, expected 0) (ArgumentError)\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/command/base.rb:69:in `perform'\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/command.rb:46:in `invoke'\n\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/commands.rb:18:in `<top (required)>'\n\tfrom bin/rails:4:in `require'\n\tfrom bin/rails:4:in `<main>'", "stderr_lines": ["/opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:506:in `handle_argument_error': ERROR: \"rails console\" was called with arguments [\"production\"] (Thor::InvocationError)", "Usage: \"rails console [options]\"", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:34:in `rescue in run'", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:20:in `run'", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/command/base.rb:69:in `perform'", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/command.rb:46:in `invoke'", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/commands.rb:18:in `<top (required)>'", "\tfrom bin/rails:4:in `require'", "\tfrom bin/rails:4:in `<main>'", "/opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/commands/console/console_command.rb:95:in `perform': wrong number of arguments (given 1, expected 0) (ArgumentError)", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/command/base.rb:69:in `perform'", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/command.rb:46:in `invoke'", "\tfrom /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/commands.rb:18:in `<top (required)>'", "\tfrom bin/rails:4:in `require'", "\tfrom bin/rails:4:in `<main>'"], "stdout": "", "stdout_lines": []}

PLAY RECAP **********************************************************************************************************************************************************************
gitlab                     : ok=29   changed=20   unreachable=0    failed=1    skipped=4    rescued=1    ignored=0   
localhost                  : ok=68   changed=36   unreachable=0    failed=0    skipped=6    rescued=0    ignored=0   
s1-win1                    : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s10-win1                   : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s11-win1                   : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s12-win1                   : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s13-win1                   : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s14-win1                   : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s15-win1                   : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s16-win1                   : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s2-win1                    : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s3-win1                    : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s4-win1                    : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s5-win1                    : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s6-win1                    : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s7-win1                    : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s8-win1                    : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
s9-win1                    : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
windc                      : ok=17   changed=14   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

**Comment by aenertia** [comment]
Looks like gitlab released a new el/7 package and it's broken the api

Yup looks like gitlab pushed a new version 2 days ago.

I'm going to try with the version from a week ago when I had it working specified in the vars and see what happens.

i.e: gitlab_version: "12.6.7-ce.0.el7"

https://packages.gitlab.com/gitlab/gitlab-ce

**Comment by aenertia** [comment]
Passes now with pinned version - but I do get a new error; but play is continuing to run ok now.

```
TASK [gitlab-postconfig : GitLab Post | Check if root user password is set] *****************************************************************************************************
fatal: [gitlab]: FAILED! => {"cache_control": "private, no-store", "changed": false, "connection": "close", "content": "{\"error\":\"invalid_grant\",\"error_description\":\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"}", "content_length": "213", "content_type": "application/json; charset=utf-8", "date": "Wed, 26 Feb 2020 10:29:09 GMT", "elapsed": 0, "json": {"error": "invalid_grant", "error_description": "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}, "msg": "Status code was 401 and not [200]: HTTP Error 401: Unauthorized", "pragma": "no-cache", "redirected": false, "server": "nginx", "status": 401, "url": "https://gitlab.ansibleworkshop.com/oauth/token", "www_authenticate": "Bearer realm=\"Doorkeeper\", error=\"invalid_grant\", error_description=\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"", "x_request_id": "EZJP0wf3xva", "x_runtime": "0.716576"}

```

**Comment by oatakan** [comment]
fixed in develop, closing. see: https://github.com/mgmt-sa-tiger-team/skylight/pull/94
